"""Trace-replay CLI — pulls a run from LangSmith and scaffolds a regression test.

Usage:
    uv run python -m app.cli.replay <thread_id>

Output:
    A new file under tests/regressions/test_replay_<thread_id_short>.py that
    instantiates a ``FakeChatModel`` pre-loaded with the LLM responses recorded
    in the LangSmith trace, then runs the graph and asserts the trajectory
    matches the production trace.

This is the trace-replay-fix loop, automated up to "fix":
    1. A real production run misbehaved.
    2. ``replay <thread_id>`` snapshots the inputs + LLM responses as a test.
    3. Student fills in the assertion that captures the bug.
    4. Student fixes the underlying code; the test now passes.
    5. The test stays in tests/regressions/ forever — re-running CI keeps the
       bug from coming back.

Requires ``LANGSMITH_API_KEY`` and ``LANGSMITH_PROJECT``. For an offline
alternative that reads the local Redis checkpointer, see ``replay_local.py``.
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

from app.config import get_settings
from app.core.logging import configure_logging, get_logger

log = get_logger(__name__)

REGRESSIONS_DIR = Path(__file__).resolve().parent.parent.parent / "tests" / "regressions"


_TEST_TEMPLATE = '''"""Regression for thread_id={thread_id}.

Generated by `app.cli.replay`. The recorded LLM responses below come from a
real production run; the assertion is intentionally minimal — fill it in to
capture the specific bug, then fix the underlying code.

DO NOT delete this file once the bug is fixed. Regression tests stay forever.
"""

import pytest

from app.agents.graph import build_graph
from app.testing.fakes import FakeChatModel
from langgraph.checkpoint.memory import MemorySaver


# Recorded LLM responses, in invocation order.
_RECORDED_RESPONSES = {responses!r}


@pytest.mark.usefixtures("settings_override")
async def test_replay_{slug}(patch_chat_model) -> None:
    fake = patch_chat_model(FakeChatModel(responses=_RECORDED_RESPONSES))

    graph = build_graph(checkpointer=MemorySaver())
    initial = {initial_state!r}
    config = {{"configurable": {{"thread_id": "regression-{slug}"}}}}
    final = await graph.ainvoke(initial, config=config)

    # TODO: replace with the assertion that captures the bug.
    # Examples:
    #   assert final["report"], "report must be non-empty"
    #   assert "lithium" in final["report"].lower()
    #   assert final["step_count"] <= 6
    assert final is not None  # placeholder
    assert len(fake.call_history) == len(_RECORDED_RESPONSES), (
        "fake exhausted exactly the canned responses"
    )
'''


def _thread_filter(thread_id: str) -> str:
    """Build the LangSmith filter expression for a thread id."""
    return (
        f"has(extra, 'metadata.thread_id') and "
        f'extra.metadata.thread_id = "{thread_id}"'
    )


def _slug(thread_id: str) -> str:
    """Make a filesystem-safe identifier from a thread id."""
    safe = re.sub(r"[^a-z0-9]+", "_", thread_id.lower())[:32]
    return safe.strip("_") or "unknown"


def _extract_initial_state(run: Any) -> dict[str, Any]:
    """Pull the original input from the root run."""
    inputs = getattr(run, "inputs", None) or {}
    if isinstance(inputs, dict):
        return inputs
    return {"raw": str(inputs)}


def _extract_responses_for_thread(client: Any, thread_id: str) -> list[Any]:
    """Walk the project's runs, filter by thread_id, return chat-model outputs."""
    settings = get_settings()
    runs = list(
        client.list_runs(
            project_name=settings.langsmith_project,
            filter=_thread_filter(thread_id),
            run_type="llm",
        )
    )
    runs.sort(key=lambda r: getattr(r, "start_time", 0))
    out: list[Any] = []
    for run in runs:
        outputs = getattr(run, "outputs", None) or {}
        # LangSmith stores chat outputs in different places depending on the
        # version; check the obvious ones in priority order.
        text = (
            outputs.get("output")
            or outputs.get("generations")
            or outputs.get("content")
            or outputs
        )
        out.append(text if isinstance(text, str) else json.dumps(text))
    return out


def _root_run(client: Any, thread_id: str) -> Any | None:
    settings = get_settings()
    runs = list(
        client.list_runs(
            project_name=settings.langsmith_project,
            filter=_thread_filter(thread_id),
            is_root=True,
            limit=1,
        )
    )
    return runs[0] if runs else None


def replay_to_test(thread_id: str) -> Path:
    """Generate a regression test scaffold for ``thread_id``.

    Returns the path to the new test file.

    Raises:
        RuntimeError: If LangSmith isn't configured or the thread isn't found.
    """
    settings = get_settings()
    if settings.langsmith_api_key is None:
        raise RuntimeError(
            "LANGSMITH_API_KEY is not set. Use `app.cli.replay_local` for offline replay."
        )

    from langsmith import Client

    client = Client()
    root = _root_run(client, thread_id)
    if root is None:
        raise RuntimeError(f"no root run found for thread_id={thread_id}")
    initial_state = _extract_initial_state(root)
    responses = _extract_responses_for_thread(client, thread_id)
    if not responses:
        raise RuntimeError(
            f"no LLM child runs found for thread_id={thread_id}; "
            "is tracing actually enabled in the run that produced this trace?"
        )

    REGRESSIONS_DIR.mkdir(parents=True, exist_ok=True)
    slug = _slug(thread_id)
    target = REGRESSIONS_DIR / f"test_replay_{slug}.py"
    target.write_text(
        _TEST_TEMPLATE.format(
            thread_id=thread_id,
            slug=slug,
            responses=responses,
            initial_state=initial_state,
        ),
        encoding="utf-8",
    )
    log.info("regression_scaffold_written", path=str(target), responses=len(responses))
    return target


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="cp3-replay",
        description="Replay a LangSmith trace as a regression test.",
    )
    parser.add_argument("thread_id", help="The thread_id of the run to replay.")
    args = parser.parse_args()

    settings = get_settings()
    configure_logging(level=settings.log_level, env=settings.app_env)

    try:
        path = replay_to_test(args.thread_id)
    except Exception as exc:
        log.error("replay_failed", error=str(exc))
        sys.exit(2)

    print(f"Regression scaffold written to {path}")
    print("Next steps:")
    print("  1. Open the file, replace the placeholder assertion with one that captures the bug.")
    print("  2. Run `uv run pytest tests/regressions/` — confirm the test fails as expected.")
    print("  3. Fix the underlying code; re-run pytest until it passes.")


if __name__ == "__main__":
    main()
