"""Shared pytest fixtures for CP3.

What's new vs CP2's conftest:

- ``fake_llm`` now produces an ``app.testing.fakes.FakeChatModel`` (not the
  inline class CP2 had) and patches BOTH the canonical ``app.agents.llm`` and
  the ``app.agents.nodes._llm`` shim. Tests that want fine-grained schema
  responses use ``patch_chat_model`` from ``app.testing.fixtures`` directly.
- ``deterministic_mode`` autouse fixture forces ``TEST_DETERMINISTIC=true``
  so any seeded behavior is reproducible.
- DB fixture uses ``cp3_db_test`` (was ``cp2_db_test``).

The DB / Redis / lifespan fixtures stay close to CP2's so existing
integration tests work after the move into ``tests/integration/``.
"""

import asyncio
from collections.abc import AsyncIterator, Generator
from typing import Any

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy import text
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    async_sessionmaker,
    create_async_engine,
)

from app.agents import llm as llm_module
from app.agents.nodes import _llm as legacy_llm
from app.agents.nodes.researcher import ResearchOutput
from app.agents.nodes.supervisor import SupervisorDecision
from app.agents.state import Finding
from app.db.base import Base
from app.testing.fakes import FakeChatModel

POSTGRES_ADMIN_URL = "postgresql+asyncpg://postgres:postgres@localhost:5433/postgres"
TEST_DB_NAME = "cp3_db_test"
TEST_DB_URL = f"postgresql+asyncpg://postgres:postgres@localhost:5433/{TEST_DB_NAME}"
REDIS_URL = "redis://localhost:6379/15"


# ---------------------------------------------------------------------------
# Auto-on deterministic mode
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _force_deterministic(monkeypatch: pytest.MonkeyPatch) -> Generator[None, None, None]:
    """Force-on deterministic switches for every test, no opt-in needed.

    Also disables the queue layer by default. Tests that exercise the queue
    (``tests/queue/*``, ``tests/integration/test_long_running_tool.py`` etc.)
    flip ``ENABLE_QUEUE=true`` themselves.
    """
    monkeypatch.setenv("DETERMINISTIC_MODE", "true")
    monkeypatch.setenv("TEST_DETERMINISTIC", "true")
    monkeypatch.setenv("ENABLE_QUEUE", "false")
    monkeypatch.setenv("ENABLE_QUEUE_FALLBACK", "false")
    yield


# ---------------------------------------------------------------------------
# Settings override
# ---------------------------------------------------------------------------


@pytest.fixture
def settings_override(monkeypatch: pytest.MonkeyPatch) -> Generator[None, None, None]:
    monkeypatch.setenv("LLM_PROVIDER", "anthropic")
    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key")
    monkeypatch.setenv("APP_ENV", "local")
    monkeypatch.setenv("LOG_LEVEL", "WARNING")
    monkeypatch.setenv("DATABASE_URL", TEST_DB_URL)
    monkeypatch.setenv("REDIS_URL", REDIS_URL)
    monkeypatch.setenv("LANGSMITH_TRACING", "false")  # never trace from tests
    from app.config import get_settings

    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


# ---------------------------------------------------------------------------
# Default fake LLM
# ---------------------------------------------------------------------------
#
# This fixture exists for the existing CP2 integration tests that just need
# *some* fake plugged in to drive a full graph run. New unit tests should use
# ``patch_chat_model`` directly with carefully-constructed responses.


def _default_fake() -> FakeChatModel:
    """Build a FakeChatModel that drives a full graph run end-to-end."""
    happy_report = (
        "# fake topic\n\n"
        "A short fake introduction generated by the test fake LLM.\n\n"
        "## Findings\n\n"
        "### F1\nFake summary one used in tests.\n\n"
        "### F2\nFake summary two used in tests.\n\n"
        "## Limitations\n\n"
        "Fake limitations section. The fake LLM does not generate real content. "
        "These extra words pad the report so any downstream length check passes."
    )
    fake = FakeChatModel(
        by_schema={
            ResearchOutput: ResearchOutput(
                findings=[
                    Finding(title="F1", summary="s1", confidence=0.9, source_hint="src1"),
                    Finding(title="F2", summary="s2", confidence=0.7, source_hint="src2"),
                    Finding(title="F3", summary="s3", confidence=0.5, source_hint="src3"),
                ]
            ),
        },
        responses=[
            # Critic + writer each call .ainvoke once per supervisor cycle. The
            # supervisor's structured-output calls are handled by ``by_schema``.
            happy_report,
            happy_report,
            happy_report,
            happy_report,
            happy_report,
            happy_report,
        ],
    )
    # Add the supervisor decisions as an ordered list keyed by schema. The
    # FakeChatModel's by_schema accepts a callable later if we want, but for
    # now we hand-roll an iterator via repeated entries.
    sup_seq = ["researcher", "critic", "writer", "done"]
    decisions = [
        SupervisorDecision(next_agent=n, reasoning="fake")  # type: ignore[arg-type]
        for n in sup_seq
    ]
    # Patch the schema-map to use a stateful iterator wrapper.
    fake._by_schema[SupervisorDecision] = _SequenceCycler(decisions)  # type: ignore[assignment]
    return fake


class _SequenceCycler:
    """Wraps a sequence so the FakeChatModel emits one item per invocation.

    Returned via ``by_schema`` — the dispatcher detects it via ``__iter__``
    being one-shot and pulls the next value.
    """

    def __init__(self, values: list[Any]) -> None:
        self._values = values
        self._cursor = 0

    def next(self) -> Any:
        if self._cursor >= len(self._values):
            return self._values[-1]
        v = self._values[self._cursor]
        self._cursor += 1
        return v


# Wire the cycler into FakeChatModel.dispatch by monkey-patching at fixture
# setup time. This keeps ``fakes.py`` clean of test-only branches.

_ORIGINAL_DISPATCH = FakeChatModel._dispatch


async def _cycler_aware_dispatch(self, *, messages, schema, kwargs):  # type: ignore[no-untyped-def]
    """Duck-type any value with a callable ``.next`` as a per-call cycler.

    Tests in different files define their own tiny cycler classes; we don't
    want a registry. If the by_schema entry has ``.next()``, treat it as
    stateful.
    """
    if schema is not None:
        bound = self._by_schema.get(schema)
        if bound is not None and callable(getattr(bound, "next", None)):
            from app.testing.fakes import _CallRecord, _render

            self.call_history.append(
                _CallRecord(
                    messages_repr=_render(messages), schema=schema, kwargs=dict(kwargs)
                )
            )
            return bound.next()
    return await _ORIGINAL_DISPATCH(self, messages=messages, schema=schema, kwargs=kwargs)


FakeChatModel._dispatch = _cycler_aware_dispatch  # type: ignore[assignment]


@pytest.fixture
def fake_llm(monkeypatch: pytest.MonkeyPatch) -> FakeChatModel:
    """Install a default-shaped FakeChatModel that drives a full graph run.

    Patches both the new ``app.agents.llm.get_chat_model`` and the legacy
    ``app.agents.nodes._llm.get_llm`` shim so any node code (existing or
    refactored) sees the fake.
    """
    fake = _default_fake()
    monkeypatch.setattr(llm_module, "get_chat_model", lambda _role, **_kwargs: fake)
    monkeypatch.setattr(legacy_llm, "get_llm", lambda _settings, **_kwargs: fake)
    return fake


@pytest.fixture
def patch_chat_model(monkeypatch: pytest.MonkeyPatch):
    """Custom-tailored fake. Tests that want exact control over the response
    map use this instead of ``fake_llm``."""

    def _install(fake: FakeChatModel) -> FakeChatModel:
        monkeypatch.setattr(llm_module, "get_chat_model", lambda _role, **_kwargs: fake)
        monkeypatch.setattr(legacy_llm, "get_llm", lambda _settings, **_kwargs: fake)
        return fake

    return _install


# ---------------------------------------------------------------------------
# Trajectory recorder
# ---------------------------------------------------------------------------


@pytest.fixture
def trajectory_recorder():
    from app.testing.recorders import TrajectoryRecorder

    return TrajectoryRecorder()


# ---------------------------------------------------------------------------
# Queue test helpers (CP4)
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def fake_redis() -> AsyncIterator[Any]:
    """In-process redis stand-in. No live Redis required.

    fakeredis emulates the wire protocol; redis.asyncio.Redis-equivalent
    methods (``set``/``get``/``lpush``/``lrange``/``lrem``/etc.) are all
    available. This fixture is used by every CP4 queue/worker test.
    """
    import fakeredis.aioredis

    client = fakeredis.aioredis.FakeRedis(decode_responses=False)
    yield client
    await client.flushdb()
    await client.aclose()


# ---------------------------------------------------------------------------
# Checkpointer fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def memory_checkpointer() -> Any:
    """An in-memory checkpointer — works without Redis."""
    from langgraph.checkpoint.memory import MemorySaver

    return MemorySaver()


# ---------------------------------------------------------------------------
# DB fixtures (Postgres)
# ---------------------------------------------------------------------------


async def _postgres_reachable() -> bool:
    try:
        engine = create_async_engine(POSTGRES_ADMIN_URL, isolation_level="AUTOCOMMIT")
        async with engine.connect() as conn:
            await conn.execute(text("SELECT 1"))
        await engine.dispose()
        return True
    except Exception:
        return False


@pytest_asyncio.fixture(scope="session")
async def test_db_engine() -> AsyncIterator[AsyncEngine]:
    """(Re)create a clean ``cp3_db_test`` and yield an engine bound to it."""
    if not await _postgres_reachable():
        pytest.skip("Postgres not reachable at localhost:5433; skipping DB-bound tests")

    admin_engine = create_async_engine(POSTGRES_ADMIN_URL, isolation_level="AUTOCOMMIT")
    async with admin_engine.connect() as conn:
        await conn.execute(text(f'DROP DATABASE IF EXISTS "{TEST_DB_NAME}" WITH (FORCE)'))
        await conn.execute(text(f'CREATE DATABASE "{TEST_DB_NAME}"'))
    await admin_engine.dispose()

    engine = create_async_engine(TEST_DB_URL, future=True)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield engine
    await engine.dispose()

    admin_engine = create_async_engine(POSTGRES_ADMIN_URL, isolation_level="AUTOCOMMIT")
    async with admin_engine.connect() as conn:
        await conn.execute(text(f'DROP DATABASE IF EXISTS "{TEST_DB_NAME}" WITH (FORCE)'))
    await admin_engine.dispose()


@pytest_asyncio.fixture
async def test_sessionmaker(
    test_db_engine: AsyncEngine,
) -> AsyncIterator[async_sessionmaker]:
    factory = async_sessionmaker(test_db_engine, expire_on_commit=False)
    yield factory
    async with test_db_engine.begin() as conn:
        for table in reversed(Base.metadata.sorted_tables):
            await conn.execute(text(f'TRUNCATE TABLE "{table.name}" CASCADE'))


# ---------------------------------------------------------------------------
# App / client fixtures
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def async_client(
    settings_override: None,
    fake_llm: FakeChatModel,
    memory_checkpointer: Any,
    test_sessionmaker: async_sessionmaker,
) -> AsyncIterator[AsyncClient]:
    """ASGI client with a real test DB and an in-memory checkpointer."""
    from asgi_lifespan import LifespanManager

    from app.main import create_app

    app = create_app(checkpointer=memory_checkpointer, sessionmaker=test_sessionmaker)
    async with LifespanManager(app):
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as client:
            yield client


@pytest_asyncio.fixture
async def background_done() -> AsyncIterator[None]:
    yield
    await asyncio.sleep(0)
